events {
    worker_connections 1024;
}

http {
    server {
        
        listen 80;
        server_name 2.26.249.198;

        location / {
            proxy_pass http://frontend:80/;
            
        }
        location /api/ {
            proxy_pass http://backend:8000/;
            
        }
    }
}